CREATE TABLE users(
ID VARCHAR(255) UNIQUE NOT NULL,
phoneNumber INT UNIQUE NOT NULL,
pass VARCHAR(255) NOT NULL,
FName VARCHAR(255) NOT NULL,
LName VARCHAR(255) NOT NULL,
PRIMARY KEY(ID, phoneNumber)
);

